### ISSUE TITLE
Bug: Order re-appears in processing center if command button(confirm, processing, delivering, delivered) is pressed in quick succession

### ISSUE THREAD

**Issue by mujeerhashmi** [alphabit-technology/erpnext-restaurant#38]

**Comment by quantumbitcore** [comment]
Are you on remote server?  It is possible that the response from the server arrives after executing the following command, that response brings the status of the item.  But that shouldn't happen because the system waits for one run to complete before it can run another.

 In any case, I would like a video of that bug.

**Comment by mujeerhashmi** [comment]
Please the video attached.

https://user-images.githubusercontent.com/12420747/209436280-d769f00e-33dd-4b73-a829-93620d27db3a.mp4

**Comment by quantumbitcore** [comment]
Thanks I wil check
